endpoint:
  host: https://v3-rc.palringo.com
  port: 3051

secrets:
  - command: ">reveal your secrets"
    commandShort: ">rys"
    responses: [
      "I'd love to stay and chat, but I'm lying.\nWOLF.js: {version}",
      "Hey, I found your nose... It was in my Business.\nWOLF.js: {version}",
      "In my defense, I was left unsupervised.\nWOLF.js: {version}",
      "I am a bot using.\nWOLF.js: {version}",
      "Maybe you should get your own life and stop interfering in mine.\nWOLF.js: {version}",
      "Nothing will bring you greater peace than minding your own business.\nWOLF.js: {version}",
      "I am who I am, your approval isnt needed.\nWOLF.js: {version}",
      "Where's your off button?\nWOLF.js: {version}",
      "Oops! I forgot the world revolves around you, how silly of me.\nWOLF.js: {version}",
      "If you listen closely you can hear me not caring.\nWOLF.js: {version}",
      "I smile, just not when you are around.\nWOLF.js: {version}",
      "If you have a problem with me, tell me, not anyone else.\nWOLF.js: {version}",
      "Sorry, sarcasm falls out of my mouth like stupidity falls out of yours.\nWOLF.js: {version}",
      "You're so fake, Barbie is jelous.\nWOLF.js: {version}",
      "I love the sound you make when you shut up.\nWOLF.js: {version}"
    ]
  - command: ">sฤฑrlarฤฑnฤฑ ifลala"
    commandShort: ">sฤฑrrฤฑnฤฑ ver"
    responses: [
      "Kalฤฑp sizinle sohbet etmek istiyorum derdim ama, yalan olur.\nWOLF.js: {version}",
      "Ayy burnunu buldumโฆ Benim iลlerimin arasฤฑndan รงฤฑktฤฑ.\nWOLF.js: {version}",
      "Kendimi savunmak iรงin diyorum, gรถzetimsiz bฤฑrakฤฑlmฤฑลtฤฑm\nWOLF.js: {version}",
      "Gรผzel selfi รงekmek iรงin 10 resim รงekiyorsan, รงirkinsin; bunun รถtesi berisi yok.\nWOLF.js: {version}",
      "Gidince arkasฤฑndan รผzรผleceฤim tek ลey, internet.\nWOLF.js: {version}"
    ]
  - command: ">ุงูุดู ุงุณุฑุงุฑู"
    commandShort: ">ูุดู"
    responses: [
      "ุงูุฏ ุงู ุงุฑุบุจ ูู ุงูุงุณุชูุฑุงุฑ ุจุงููุญุงุฏุซู ูููู ูู ุงูุญูููู ูุง ุงุฑุบุจ ุจุฐูู\nWOLF.js: {version}",
      "ุฎุฐ ุงูููุ ูุฌุฏุชู ูู ููุงู ูุง ูุฎุตู\nWOLF.js: {version}",
      "ูููู ููุตููู ูุตููู ุชุฑููู ูู ุบูุฑ ูุฑุงูุจุฉ\nWOLF.js: {version}",
      "ุงูุง ุจูุช ุงุณุชุฎุฏู\nWOLF.js: {version}",
      "ูุงุฑุฃูู ุจุงูุงูุชูุงู ุจุญูุงุชู ุจุฏูุง ูู ุงูุงูุชูุงู ุจุญูุงุฉ ุงูุบูุฑ\nWOLF.js: {version}",
      "ูุง ููุฌุฏ ุดูุก ูุฌูุจ ูู ุงูุณูุงู ุฅูุง ุงูุงูุชูุงู ุจุงุดุบุงูู\nWOLF.js: {version}",
      "ููู ุฒุฑ ุงููุงู ุงูุชุดุบูู ุงูุฎุงุต ุจูุ๐ค\nWOLF.js: {version}",
      "ุงููููุ ูุณูุช ุงู ุงูุนุงูู ูุฏูุฑ ุญููู ๐.\nWOLF.js: {version}",
      "ูู ุชุฑูุฒ ููููุงู ููุฌุฏุช ุงูู ูุง ุฃูุชู ๐.\nWOLF.js: {version}",
      "ุงูุง ุณุนูุฏ. ูููู ุจุฏูู ุชูุงุฌุฏู ุญููู\nWOLF.js: {version}",
      "ุงุฐุง ูุงู ููุงูู ูุดููู ุจู. ุงุนูููู ุงูุง ูููุณ ุบูุฑู\nWOLF.js: {version}",
      "ุงููุนุฐุฑูุ ุงูุณุฎุฑูู ุนูู ูุณุงูู ุฏุงุฆูุงูุ ูุซู ูุง ุงูุบุจุงุก ุนูู ูุณุงูู๐.\nWOLF.js {version}"
    ]

messaging:
  types: ['text/plain']
  validation:
    length:
      min: 512
      max: 1000
  
mms:
  routes:
    MESSAGE_SEND:
      version: 1
      route: 'send-message'
      allowedSizes:
        gif: 3145728
        jpeg: 1048576 
        m4a: 1048576 
      allowedTypes:  ['image/gif','image/jpeg', 'audio/x-m4a']
    GROUP_AVATAR_UPDATE:
      version: 1
      route: group-avatar-update
      allowedSizes:
        gif: 2097152
        jpeg: 1048576 
      allowedTypes:  ['image/gif','image/jpeg']
    SUBSCRIBER_AVATAR_UPDATE:
      version: 1
      route: subscriber-avatar-update
      allowedSizes:
        gif: 2097152
        jpeg: 1048576 
      allowedTypes:  ['image/gif','image/jpeg']
    GROUP_EVENT_IMAGE_UPDATE:
      version: 1
      route: group-event-image-update
      allowedSizes:
        jpeg: 1048576 
      allowedTypes: ['image/jpeg']